<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Snippet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\\\$|\\`|\\\\</string>
			<key>name</key>
			<string>constant.character.escape.tm-snippet</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#transformations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tab_stops</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interpolation</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.tm-snippet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.tm-snippet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.interpolated.bash.tm-snippet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\`|\\\\</string>
					<key>name</key>
					<string>constant.character.escape.tm-snippet</string>
				</dict>
			</array>
		</dict>
		<key>tab_stops</key>
		<dict>
			<key>comment</key>
			<string>FINISHED</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.tm-snippet</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>$0 | ${0}</string>
					<key>match</key>
					<string>(\$)(0(?!=\d)|(\{)0(?!=\d)(\}))</string>
					<key>name</key>
					<string>variable.other.predefined.placeholder.endpoint.tm-snippet</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)\d+</string>
					<key>name</key>
					<string>variable.other.predefined.placeholder.tm-snippet</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.tm-snippet</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$\{)\d+(\})</string>
					<key>name</key>
					<string>variable.other.predefined.placeholder.tm-snippet</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\$\{)\d+(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.default-value.tm-snippet</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.tm-snippet</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.other.predefined.placeholder.w-default.tm-snippet</string>
				</dict>
			</array>
		</dict>
		<key>transformations</key>
		<dict>
			<key>begin</key>
			<string>(\$\{)\d+(?=/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.tm-snippet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.tm-snippet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.other.predefined.placeholder.transform.tm-snippet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=/)</string>
					<key>end</key>
					<string>(?=\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?!/)</string>
							<key>end</key>
							<string>(?=/)</string>
							<key>name</key>
							<string>string.other.CHANGETHIS.tm-snippet</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(\$)\d+</string>
									<key>name</key>
									<string>variable.other.predefined.register.tm-snippet</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\[ulULE]</string>
									<key>name</key>
									<string>constant.other.reference.tm-snippet</string>
								</dict>
								<dict>
									<key>comment</key>
									<string>ASK ABOUT \( HERE AND IN VARIABLES</string>
									<key>match</key>
									<string>\\[nt$\\]</string>
									<key>name</key>
									<string>constant.character.escape.tm-snippet</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>\(\?\d+:</string>
									<key>end</key>
									<string>\)</string>
									<key>name</key>
									<string>meta.conditional-insertion.tm-snippet</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(/)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.regexp.tm-snippet</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.tm-snippet</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>comment</key>
									<string>ASK ALLAN ABOUT THIS, IS INCOMPLETE.</string>
									<key>match</key>
									<string>(?&lt;=/)([imx]+-?[imx]+|-?[imx]+)</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\S</string>
									<key>name</key>
									<string>invalid.illegal.character-not-allowed-here.tm-snippet</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.regexp.tm-snippet</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.tm-snippet</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(/)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.regexp.tm-snippet</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.tm-snippet</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.tm-snippet</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp.oniguruma</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Take care of the built-in dynamic environment variables.</string>
					<key>match</key>
					<string>(\$)TM_(BUNDLE_SUPPORT|S(COPE|OFT_TABS|UPPORT_PATH|ELECTED_(TEXT|FILE(S)?))|CURRENT_(WORD|LINE)|TAB_SIZE|DIRECTORY|PROJECT_DIRECTORY|FILEPATH|LINE_(NUMBER|INDEX))</string>
					<key>name</key>
					<string>variable.other.predefined.tm-snippet</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>User defined variables.</string>
					<key>match</key>
					<string>(\$)[A-Za-z_][A-Za-z0-9_]*</string>
					<key>name</key>
					<string>variable.other.readwrite.tm-snippet</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.tm-snippet</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>User defined variables.</string>
					<key>match</key>
					<string>(\$\{)[A-Za-z_][A-Za-z0-9_]*(\})</string>
					<key>name</key>
					<string>variable.other.readwrite.tm-snippet</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\$\{)[A-Za-z_][A-Za-z0-9_]*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.options.tm-snippet</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>User defined variables.</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.tm-snippet</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.other.readwrite.tm-snippet</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\$\{)[A-Za-z_][A-Za-z0-9_]*(?=/)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.tm-snippet</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.tm-snippet</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.other.readwrite.tm-snippet</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=/)</string>
							<key>end</key>
							<string>(?=\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?!/)</string>
									<key>end</key>
									<string>(?=/)</string>
									<key>name</key>
									<string>string.other.CHANGETHIS.tm-snippet</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>(\$)\d+</string>
											<key>name</key>
											<string>variable.other.predefined.register.tm-snippet</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\\[ulULE]</string>
											<key>name</key>
											<string>constant.other.reference.tm-snippet</string>
										</dict>
										<dict>
											<key>comment</key>
											<string>ASK ABOUT \( HERE AND IN VARIABLES</string>
											<key>match</key>
											<string>\\[nt$\\]</string>
											<key>name</key>
											<string>constant.character.escape.tm-snippet</string>
										</dict>
										<dict>
											<key>begin</key>
											<string>\(\?\d+:</string>
											<key>end</key>
											<string>\)</string>
											<key>name</key>
											<string>meta.conditional-insertion.tm-snippet</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>(/)</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>string.regexp.tm-snippet</string>
										</dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.tm-snippet</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(?=\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>comment</key>
											<string>ASK ALLAN ABOUT THIS, IS INCOMPLETE.</string>
											<key>match</key>
											<string>(?&lt;=/)([imx]+)?(-[imx]+)?</string>
										</dict>
										<dict>
											<key>match</key>
											<string>\S</string>
											<key>name</key>
											<string>invalid.illegal.character-not-allowed-here.tm-snippet</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(/)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.regexp.tm-snippet</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.tm-snippet</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(/)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.regexp.tm-snippet</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.tm-snippet</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.regexp.tm-snippet</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.regexp.oniguruma</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tm-snippet</string>
	<key>uuid</key>
	<string>95BE73A9-82E2-493A-B467-013B4B2ECAD2</string>
</dict>
</plist>
