<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>TextMate Settings</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?=\{)</string>
			<key>end</key>
			<string>(?=not)possible</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dictionary_root</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stray</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#stray</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\G\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.plist</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.plist</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.scope.array.plist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#array_item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stray</string>
				</dict>
			</array>
		</dict>
		<key>array_item</key>
		<dict>
			<key>begin</key>
			<string>(?=&lt;|\(|\{|"|'|[-a-zA-Z0-9_.])</string>
			<key>end</key>
			<string>,|(?=\))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.array.plist</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.scope.array-item.plist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dictionary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stray</string>
				</dict>
			</array>
		</dict>
		<key>dictionary</key>
		<dict>
			<key>begin</key>
			<string>\G\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.plist</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.plist</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.scope.dictionary.plist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dictionary_item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stray</string>
				</dict>
			</array>
		</dict>
		<key>dictionary_item</key>
		<dict>
			<key>begin</key>
			<string>(?&gt;((")((?:[^"\\]|\\.)*)("))|((')((?:[^'\\]|\\.)*)('))|([-a-zA-Z0-9_.]+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.plist</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.plist</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.key.plist</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.plist</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.plist</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.plist</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.other.key.plist</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.plist</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.other.key.plist</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|(?=\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.plist</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.scope.dictionary-item.${3/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}${7/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}${9/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}.plist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dictionary_item_contents</string>
				</dict>
			</array>
		</dict>
		<key>dictionary_item_contents</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>=</string>
					<key>end</key>
					<string>(?=;|\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?=&lt;|\(|\{|"|'|[-a-zA-Z0-9_.])</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#dictionary</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#array</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray_alpha</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#stray</string>
				</dict>
			</array>
		</dict>
		<key>dictionary_root</key>
		<dict>
			<key>begin</key>
			<string>\G\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.plist</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.plist</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.scope.dictionary.plist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>comment</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?="|')</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\G'</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.begin.plist</string>
												</dict>
											</dict>
											<key>end</key>
											<string>'(?!')</string>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.end.plist</string>
												</dict>
											</dict>
											<key>name</key>
											<string>comment.block.plist</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>match</key>
													<string>''</string>
													<key>name</key>
													<string>constant.character.escape.plist</string>
												</dict>
											</array>
										</dict>
										<dict>
											<key>begin</key>
											<string>\G"</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.begin.plist</string>
												</dict>
											</dict>
											<key>end</key>
											<string>"</string>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.end.plist</string>
												</dict>
											</dict>
											<key>name</key>
											<string>comment.block.plist</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>match</key>
													<string>\\("|\\)</string>
													<key>name</key>
													<string>constant.character.escape.plist</string>
												</dict>
											</array>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>completionCommand|characterClass|background|foreground|caret|invisibles|selection|fontStyle|fontName|indentOnPaste|wordCharacters</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?="|'|[-a-zA-Z0-9_.])</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#string</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray_alpha</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>indentedSoftWrap</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?=\{)</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\G\{</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.dictionary.begin.plist</string>
												</dict>
											</dict>
											<key>end</key>
											<string>\}</string>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.dictionary.end.plist</string>
												</dict>
											</dict>
											<key>name</key>
											<string>meta.scope.dictionary.plist</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>begin</key>
													<string>match</string>
													<key>beginCaptures</key>
													<dict>
														<key>0</key>
														<dict>
															<key>name</key>
															<string>constant.other.key.plist</string>
														</dict>
													</dict>
													<key>end</key>
													<string>;|(?=\})</string>
													<key>endCaptures</key>
													<dict>
														<key>0</key>
														<dict>
															<key>name</key>
															<string>punctuation.separator.dictionary.plist</string>
														</dict>
													</dict>
													<key>name</key>
													<string>meta.scope.dictionary-item.$0.plist</string>
													<key>patterns</key>
													<array>
														<dict>
															<key>begin</key>
															<string>=</string>
															<key>end</key>
															<string>(?=;|\})</string>
															<key>patterns</key>
															<array>
																<dict>
																	<key>begin</key>
																	<string>(?="|')</string>
																	<key>end</key>
																	<string>(?=;|\})</string>
																	<key>patterns</key>
																	<array>
																		<dict>
																			<key>include</key>
																			<string>#string_regexp</string>
																		</dict>
																		<dict>
																			<key>include</key>
																			<string>#stray</string>
																		</dict>
																	</array>
																</dict>
																<dict>
																	<key>include</key>
																	<string>#stray_alpha</string>
																</dict>
															</array>
														</dict>
														<dict>
															<key>include</key>
															<string>#stray</string>
														</dict>
													</array>
												</dict>
												<dict>
													<key>begin</key>
													<string>format</string>
													<key>beginCaptures</key>
													<dict>
														<key>0</key>
														<dict>
															<key>name</key>
															<string>constant.other.key.plist</string>
														</dict>
													</dict>
													<key>end</key>
													<string>;|(?=\})</string>
													<key>endCaptures</key>
													<dict>
														<key>0</key>
														<dict>
															<key>name</key>
															<string>punctuation.separator.dictionary.plist</string>
														</dict>
													</dict>
													<key>name</key>
													<string>meta.scope.dictionary-item.$0.plist</string>
													<key>patterns</key>
													<array>
														<dict>
															<key>begin</key>
															<string>=</string>
															<key>end</key>
															<string>(?=;|\})</string>
															<key>patterns</key>
															<array>
																<dict>
																	<key>begin</key>
																	<string>(?="|'|[-a-zA-Z0-9_.])</string>
																	<key>end</key>
																	<string>(?=;|\})</string>
																	<key>patterns</key>
																	<array>
																		<dict>
																			<key>include</key>
																			<string>#string</string>
																		</dict>
																		<dict>
																			<key>include</key>
																			<string>#stray_alpha</string>
																		</dict>
																	</array>
																</dict>
																<dict>
																	<key>include</key>
																	<string>#stray_alpha</string>
																</dict>
															</array>
														</dict>
														<dict>
															<key>include</key>
															<string>#stray</string>
														</dict>
													</array>
												</dict>
												<dict>
													<key>begin</key>
													<string>(?&gt;((")((?:[^"\\]|\\.)*)("))|((')((?:[^'\\]|\\.)*)('))|([-a-zA-Z0-9_.]+))</string>
													<key>beginCaptures</key>
													<dict>
														<key>1</key>
														<dict>
															<key>name</key>
															<string>string.quoted.double.plist</string>
														</dict>
														<key>2</key>
														<dict>
															<key>name</key>
															<string>punctuation.definition.string.begin.plist</string>
														</dict>
														<key>3</key>
														<dict>
															<key>name</key>
															<string>invalid.illegal.invalid_key.plist</string>
														</dict>
														<key>4</key>
														<dict>
															<key>name</key>
															<string>punctuation.definition.string.end.plist</string>
														</dict>
														<key>5</key>
														<dict>
															<key>name</key>
															<string>string.quoted.single.plist</string>
														</dict>
														<key>6</key>
														<dict>
															<key>name</key>
															<string>punctuation.definition.string.begin.plist</string>
														</dict>
														<key>7</key>
														<dict>
															<key>name</key>
															<string>invalid.illegal.invalid_key.plist</string>
														</dict>
														<key>8</key>
														<dict>
															<key>name</key>
															<string>punctuation.definition.string.end.plist</string>
														</dict>
														<key>9</key>
														<dict>
															<key>name</key>
															<string>invalid.illegal.invalid_key.plist</string>
														</dict>
													</dict>
													<key>end</key>
													<string>;|(?=\})</string>
													<key>endCaptures</key>
													<dict>
														<key>0</key>
														<dict>
															<key>name</key>
															<string>punctuation.separator.dictionary.plist</string>
														</dict>
													</dict>
													<key>name</key>
													<string>meta.scope.dictionary-item.${3/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}${7/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}${9/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}.plist</string>
													<key>patterns</key>
													<array>
														<dict>
															<key>include</key>
															<string>#dictionary_item_contents</string>
														</dict>
													</array>
												</dict>
												<dict>
													<key>include</key>
													<string>#stray</string>
												</dict>
											</array>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>fontSize</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?="|'|[-a-zA-Z0-9_.])</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\G'</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.begin.plist</string>
												</dict>
											</dict>
											<key>end</key>
											<string>'(?!')</string>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.end.plist</string>
												</dict>
											</dict>
											<key>name</key>
											<string>string.quoted.single.plist</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>captures</key>
													<dict>
														<key>1</key>
														<dict>
															<key>name</key>
															<string>constant.numeric.plist</string>
														</dict>
														<key>3</key>
														<dict>
															<key>name</key>
															<string>keyword.other.unit.plist</string>
														</dict>
													</dict>
													<key>match</key>
													<string>\G([0-9]+(\.[0-9]+)?)([ ]?(%|pt|em))?</string>
												</dict>
											</array>
										</dict>
										<dict>
											<key>begin</key>
											<string>\G"</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.begin.plist</string>
												</dict>
											</dict>
											<key>end</key>
											<string>"</string>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.end.plist</string>
												</dict>
											</dict>
											<key>name</key>
											<string>string.quoted.double.plist</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>match</key>
													<string>\G[0-9]+(\.[0-9]+)?[ ]?(%|pt|em)?</string>
													<key>name</key>
													<string>constant.numeric.plist</string>
												</dict>
											</array>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>completions|highlightPairs|smartTypingPairs|shellVariables</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?=\()</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#array</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>disableDefaultCompletion|showInSymbolList|spellChecking|misspelled|bold|italic|underline|softWrap</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?=[01])</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G[01]</string>
											<key>name</key>
											<string>constant.numeric.plist</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>(?=['"])</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>captures</key>
											<dict>
												<key>1</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.begin.plist</string>
												</dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>constant.numeric.plist</string>
												</dict>
												<key>3</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.end.plist</string>
												</dict>
											</dict>
											<key>match</key>
											<string>(')([01])(')</string>
											<key>name</key>
											<string>string.quoted.single.plist</string>
										</dict>
										<dict>
											<key>captures</key>
											<dict>
												<key>1</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.begin.plist</string>
												</dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>constant.numeric.plist</string>
												</dict>
												<key>3</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.end.plist</string>
												</dict>
											</dict>
											<key>match</key>
											<string>(")([01])(")</string>
											<key>name</key>
											<string>string.quoted.double.plist</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>(?=:)</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G:(true|false)</string>
											<key>name</key>
											<string>constant.language.boolean.plist</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>disableIndentCorrections</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?=[01])</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G[01]</string>
											<key>name</key>
											<string>constant.numeric.plist</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>(?=['"])</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>captures</key>
											<dict>
												<key>1</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.begin.plist</string>
												</dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>constant.numeric.plist</string>
												</dict>
												<key>4</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.end.plist</string>
												</dict>
											</dict>
											<key>match</key>
											<string>(')(?:([01])|(emptyLines))(')</string>
											<key>name</key>
											<string>string.quoted.single.plist</string>
										</dict>
										<dict>
											<key>captures</key>
											<dict>
												<key>1</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.begin.plist</string>
												</dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>constant.numeric.plist</string>
												</dict>
												<key>4</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.string.end.plist</string>
												</dict>
											</dict>
											<key>match</key>
											<string>(")(?:([01])|(emptyLines))(")</string>
											<key>name</key>
											<string>string.quoted.double.plist</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>(?=:)</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\G:(true|false)</string>
											<key>name</key>
											<string>constant.language.boolean.plist</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray_alpha</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>symbolTransformation|decreaseIndentPattern|increaseIndentPattern|indentNextLinePattern|unIndentedLinePattern|zeroIndentPattern|foldingStartMarker|foldingStopMarker|foldingIndentedBlockIgnore|foldingIndentedBlockStart</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.$0.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>end</key>
							<string>(?=;|\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?="|')</string>
									<key>end</key>
									<string>(?=;|\})</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#string_regexp</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#stray</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#stray_alpha</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#stray</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&gt;((")((?:[^"\\]|\\.)*)("))|((')((?:[^'\\]|\\.)*)('))|([-a-zA-Z0-9_.]+))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.plist</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.plist</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.invalid_key.plist</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.plist</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.plist</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.plist</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.invalid_key.plist</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.plist</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.invalid_key.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.dictionary-item.${3/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}${7/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}${9/[[\s\x20-\x7F]&amp;&amp;[:^alnum:]]//g}.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dictionary_item_contents</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#stray</string>
				</dict>
			</array>
		</dict>
		<key>stray</key>
		<dict>
			<key>begin</key>
			<string>\S</string>
			<key>end</key>
			<string>(?=\{|\(|/\*|//|"|'|&lt;|,|;|\)|\}|=)</string>
			<key>name</key>
			<string>invalid.illegal.character-not-allowed-here.plist</string>
		</dict>
		<key>stray_alpha</key>
		<dict>
			<key>begin</key>
			<string>\S</string>
			<key>end</key>
			<string>(?=\{|\(|/\*|//|"|'|&lt;|,|;|\)|\}|=|\b[a-zA-Z0-9]|[-_.])</string>
			<key>name</key>
			<string>invalid.illegal.character-not-allowed-here.plist</string>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'(?!')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>''</string>
							<key>name</key>
							<string>constant.character.escape.plist</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\("|\\)</string>
							<key>name</key>
							<string>constant.character.escape.plist</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\G[-+]?\d+(\.\d*)?(E[-+]\d+)?(?!\w)</string>
					<key>name</key>
					<string>constant.numeric.plist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G[-a-zA-Z0-9_.]+</string>
					<key>name</key>
					<string>string.unquoted.plist</string>
				</dict>
			</array>
		</dict>
		<key>string_regexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'(?!')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>''</string>
							<key>name</key>
							<string>constant.character.escape.plist</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.regexp.oniguruma</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.plist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.plist</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.plist</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\("|\\)</string>
							<key>name</key>
							<string>constant.character.escape.plist</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.regexp.oniguruma</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.plist.textmate.settings</string>
	<key>uuid</key>
	<string>CF3947B5-C5CE-46A1-8E84-724C6C986861</string>
</dict>
</plist>
